module.exports = {
    MAKE_POST: "MAKE_POST",
    EDIT_POST: "EDIT_POST",
    DELETE_POST:"DELETE_POST",
    EDIT_FROM: "EDIT_FROM",
    EDIT_TO: "EDIT_TO",
    EDIT_CAN_WAIT: "EDIT_CAN_WAIT",
    EDIT_NUMBER_OF_CLIENTS: "EDIT_NUMBER_OF_CLIENTS",
    EDIT_PHONE_NUMBER: "EDIT_PHONE_NUMBER",
    EDIT_DESC: "EDIT_DESC",
    EDIT_GO_BACK: "EDIT_GO_BACK",
    TAXI_FOUND: "TAXI_FOUND",
    I_FOUND_TAXI: "I_FOUND_TAXI",
    I_DIDNT_FIND_TAXI: "I_DIDNT_FIND_TAXI"
}
