module.exports = {
    START: "START",
    FROM: "FROM",
    TO: "TO",
    CAN_WAIT: "CAN_WAIT",
    NUMBER_OF_CLIENTS: "NUMBER_OF_CLIENTS",
    PHONE_NUMBER: "PHONE_NUMBER",
    DESC: "DESC",
    REVIEW: "REVIEW",

    // EDIT STATE
    EDIT_FROM: "EDIT_FROM",
    EDIT_TO: "EDIT_TO",
    EDIT_CAN_WAIT: "EDIT_CAN_WAIT",
    EDIT_NUMBER_OF_CLIENTS: "EDIT_NUMBER_OF_CLIENTS",
    EDIT_PHONE_NUMBER: "EDIT_PHONE_NUMBER",
    EDIT_DESC: "EDIT_DESC",

}